#CountOnMe Makefile

help:
	@echo "Simple calculator named CountOnMe																				"
	@echo "Usage: make (OPTIONS)																							"
	@echo "-----------------------------------------------------------------------------------------------------------------"
	@echo "OPTIONS: (please choose one of the options below)					  		 									"
	@echo "	help: 	 prints usage of the Makefile (with a description of what needs to be done before starting the program) "
	@echo "	all:  	 compiles the whole project, including the profiling program											"
	@echo "	pack: 	 zips the project so that it can be submitted															"
	@echo "	test: 	 runs math library tests																				"
	@echo "	run:	 runs the calculator																					"
	@echo "	doc:	 starts the documentation of the project																"
	@echo "	profile: runs the program for calculation of decisive derivant for profiling									"
	@echo "	clean: 	 deletes all files that should not be committed  													  	"

all:

pack:

clean:

test:

doc:

run:

profile: 